### ISSUE TITLE
Error On Replit

### ISSUE THREAD

**Issue by abusayed0206** [Rayanfer32/TgindexPro#22]
 python3 run.py
ERROR:telethon.network.mtprotosender:Request caused struct.error: 'I' format requires 0 <= number <= 4294967295: GetUsersRequest(id=[InputUser(user_id=1001508344724, access_hash=0)])
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/TgindexPro/app/__main__.py", line 19, in <module>
    Indexer().run()
  File "/home/runner/TgindexPro/app/main.py", line 46, in run
    self.loop.run_until_complete(self.startup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/TgindexPro/app/main.py", line 32, in startup
    await setup_routes(self.server, Views(self.tg_client))
  File "/home/runner/TgindexPro/app/routes.py", line 83, in setup_routes
    chat = await client.get_entity(chat_id)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 287, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 440, in get_input_entity
    users = await self(functions.users.GetUsersRequest([
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/client/users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 176, in send
    state = RequestState(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/tl/functions/users.py", line 72, in _bytes
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/tl/functions/users.py", line 72, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/tl/types/__init__.py", line 11928, in _bytes
    struct.pack('<I', self.user_id)

**Comment by rayanfer32** [comment]
use a channel or a group
