### ISSUE TITLE
i Can't Generate Session String

### ISSUE THREAD

**Issue by mohan585** [Rayanfer32/TgindexPro#5]
python3 app/generate_session_string.py

Traceback (most recent call last):
  File "app/generate_session_string.py", line 12, in <module>
    api_id = os.environ['API_ID']#int(input("Enter your API_ID: "))
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'API_ID'

**Comment by Rayanfer32** [comment]
You cannot keep blank keys in your .env file.... this will cause .env read
errors
